# SwiftLint configuration for SwiftKT
# https://github.com/realm/SwiftLint

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - modifier_order
  - multiline_arguments
  - redundant_nil_coalescing
  - strict_fileprivate
  - trailing_closure
  - unneeded_parentheses_in_closure_argument

disabled_rules:
  - line_length  # allow longer lines for documentation

force_unwrapping:
  severity: error

force_cast:
  severity: warning

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 50
  error: 100

excluded:
  - .build
  - DerivedData
